spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://130.162.133.248:3306/gyhDb?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: gyh
    password: rkddusgh12
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl